#' Global food security index
#'
#' A dataset containing four variables of 113 countries for their food security
#' index based on panelists evaluation.
#'
#' @format A data frame with 113 rows and 4 variables:
#' \describe{
#'   \item{affordability}{affordability}
#'   \item{availability}{availability}
#'   \item{safety}{safety}
#'   \item{resilience}{resilience}
#' }
#' @source \url{http://foodsecurityindex.eiu.com}
"globalfood"

#' 4 clustered data
#'
#' A dataset containing two variables of 300 objects and their class memberships
#' generated by a clusterGeneration package.
#'
#' @format A data frame with 300 rows and 3 variables:
#' \describe{
#'   \item{x1}{X1.}
#'   \item{x2}{X2.}
#'   \item{class}{Class membership.}
#' }
"clust4"
